services:
  app:
    build: .
    container_name: gestion-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gestionContabledb
      - NODE_ENV=development
      - PORT_APP=3000
      - HOST_APP=0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestionContabledb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: